del *.ncb /f/s/q/a
del *.ilk /f/s/q/a
del *.aps /f/s/q/a
del *.iss /f/s/q/a
del *.plg /f/s/q/a
del *.user /f/s/q/a
del Debug\*.obj /f/s/q/a
del Debug\*.sbr /f/s/q/a
del Debug\*.res /f/s/q/a
del Debug\*.pdb /f/s/q/a
del Debug\*.idb /f/s/q/a
del Debug\*.pch /f/s/q/a
del Release\*.obj /f/s/q/a
del Release\*.sbr /f/s/q/a
del Release\*.res /f/s/q/a
del Release\*.pdb /f/s/q/a
del Release\*.idb /f/s/q/a
del Release\*.pch /f/s/q/a