//------------------------------------------------------------------------------
// Header generated by wxDesigner from file: test.wdr
// Do not modify this file, all changes will be lost!
//------------------------------------------------------------------------------

#ifndef __WDR_test_H__
#define __WDR_test_H__

#if defined(__GNUG__) && !defined(NO_GCC_PRAGMA)
    #pragma interface "test_wdr.h"
#endif

// Include wxWidgets' headers

#ifndef WX_PRECOMP
    #include <wx/wx.h>
#endif

#include <wx/image.h>
#include <wx/statline.h>
#include <wx/spinbutt.h>
#include <wx/spinctrl.h>
#include <wx/splitter.h>
#include <wx/listctrl.h>
#include <wx/treectrl.h>
#include <wx/notebook.h>
#include <wx/grid.h>
#include <wx/toolbar.h>
#include <wx/tglbtn.h>

// Declare window functions

const int ID_TEXTCTRL_OUPUT = 10000;
wxSizer *MainFrameDialog( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int ID_TEXT_SRV_CONFIG = 10001;
const int ID_TEXTCTRL_CFGFILE = 10002;
const int ID_BUTTON_SELCFGFILE = 10003;
const int ID_LINE = 10004;
const int ID_TOGGLEBUTTON_SSSERVER = 10005;
const int ID_GRID_SRV_ST = 10006;
const int ID_GRID_SRC = 10007;
const int ID_BUTTON_DEL_SRC = 10008;
const int ID_TOGGLEBUTTON_SRC_SENDDATA = 10009;
const int ID_TEXT = 10010;
const int ID_SPINCTRL_SINTERVAL = 10011;
const int ID_SPINCTRL_SRC_REFINTERVAL = 10012;
const int ID_CHECKBOX_SRC_REFRESH = 10013;
const int ID_SPINCTRL_SRCIDX_START = 10014;
const int ID_SPINCTRL_SRCID_END = 10015;
const int ID_BUTTON_ADD_SINGLE = 10016;
const int ID_BUTTON_ADD_LOTS = 10017;
const int ID_TOGGLEBUTTON_AD_RAND = 10018;
const int ID_SPINCTRL_AD_INTERVAL = 10019;
const int ID_GRID_CLIENT = 10020;
const int ID_SPINCTRL_CLI_REFINTERVAL = 10021;
const int ID_CHECKBOX_CLI_REFRESH = 10022;
wxSizer *CreateTestServerDialog( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int ID_TOGGLEBUTTON_START_SECTION = 10023;
const int ID_GRID_PRO_MODULE = 10024;
const int ID_GRID_CHANNEL = 10025;
const int ID_SPINCTRL_CHN_REFINTERVAL = 10026;
const int ID_CHECKBOX_CHN_REFRESH = 10027;
const int ID_CHOICE_PRO = 10028;
const int ID_TEXTCTRL_IP = 10029;
const int ID_TEXTCTRL_PORT = 10030;
const int ID_SPINCTRL_KEYIDX_START = 10031;
const int ID_SPINCTRL_KEY_NUMBER = 10032;
const int ID_CHOICE_TRANSMODULE = 10033;
const int ID_BTN_CLOSE = 10034;
const int ID_BTN_DEL = 10035;
const int ID_TBLBTN_OCRAND = 10036;
const int ID_TGLBTN_PLAY = 10037;
const int ID_TGLBTN_PAUSE = 10038;
const int ID_BTN_FAST = 10039;
const int ID_BTN_SLOW = 10040;
const int ID_BTN_STEP = 10041;
const int ID_SLIDER_SETPOINT = 10042;
const int ID_BTN_OPEN = 10043;
wxSizer *CreateTestClientDialog( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

// Declare menubar functions

const int ID_MENU = 10044;
const int ID_MENU_SERVER = 10045;
const int ID_MENU_TEST = 10046;
const int ID_MENU_ASSERT = 10047;
wxMenuBar *MyMenuBarFunc();

// Declare toolbar functions

// Declare bitmap functions

#endif

// End of generated file
